server.port=9090
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/npi_seiko
spring.datasource.username=planning
spring.datasource.password=planning
app-base-url=http://localhost:4205
# ------ Uploaded files directory templates -----------
temporary-files-path-directory=C:/tmp/temporary-files/
process-line-files-path-directory=C:/tmp/process-line-files/
npi-order-files-path-directory=C:/tmp/npi-order-files/
# --------------SMTP-------------- #
.smtp2go.base-url=https://api.smtp2go.com/v3
.smtp2go.sender=Lokalix DEV<noreply@lokalix-sandbox.xyz>
.smtp2go.generic-email=noreply@lokalix-sandbox.xyz
.smtp2go.api-key-header=X-Smtp2go-Api-Key
.smtp2go.api-key=api-D49CA80420614C1AB58D0EE1DA2CC4C7
# --------License-----------
license-secret-key=Vs76GTCqCQtNfkdK/3n0fi0Tl/P6TqqfjKG2DByTzcM=
# --------JWT-----------
jwt-secret-key=sS1WoUjEk2kbUJ8gmN1C5xOCkDMvShwhDDfAl5TRg/0=
# --------Super admin--------
super-admin-login=superadmin
super-admin-password=a
spring.thymeleaf.prefix=classpath:/email-templates/
starting-year=2025
# When returning list of currencies, will always try to put first as follows
#--------- Excel file templates -----------
.excel-template-paths.standard-generation-excel-file-template=/Users/muss/dev/npi-seiko-core/core/src/main/resources/excel-templates/standard-generation-excel-file-template.xlsx